import { useState, useEffect } from "react";

/* ─────────────────────────────────────────────
   AIVANTAGEAFRICA  ·  CEO & AI Founder: David Mogotlane
   Zero headcount. Instant monetization. Africa's AI edge.
   ───────────────────────────────────────────── */

const COLORS = {
  void: "#050508",
  obsidian: "#0D0D12",
  carbon: "#141419",
  panel: "#1A1A22",
  border: "#2A2A38",
  amber: "#F5A623",
  gold: "#E09010",
  goldDim: "#7A4D08",
  electric: "#00E5FF",
  electricDim: "#005566",
  white: "#F8F8FF",
  muted: "#7A7A9A",
  danger: "#FF4444",
  success: "#00D084",
};

const PRODUCTS = [
  { id: 1, name: "Africa AI Prompt Vault", tag: "INSTANT DOWNLOAD", desc: "500+ battle-tested AI prompts engineered for African markets — sales, ops, marketing.", price: "R 249", usd: "$13", icon: "⚡", color: COLORS.amber, badge: "🔥 BEST SELLER", sold: 847 },
  { id: 2, name: "Solopreneur OS Africa", tag: "NOTION SYSTEM", desc: "Zero-headcount business OS. Run your entire operation with AI. Built for African founders.", price: "R 399", usd: "$22", icon: "🧠", color: COLORS.electric, badge: "✦ FEATURED", sold: 412 },
  { id: 3, name: "AI Content Machine", tag: "90-DAY SYSTEM", desc: "Full social content calendar generated by AI. LinkedIn, WhatsApp, Instagram — done.", price: "R 349", usd: "$19", icon: "📡", color: "#A855F7", badge: "🚀 NEW", sold: 203 },
  { id: 4, name: "Client Command Kit", tag: "AGENCY TOOLKIT", desc: "AI-powered proposals, onboarding, and client comms. Close more. Do less.", price: "R 299", usd: "$16", icon: "🎯", color: COLORS.success, badge: null, sold: 156 },
];

const PLANS = [
  { name: "LAUNCH", price: "FREE", sub: "Forever", features: ["3 AI generations/day", "Prompt Vault preview (50)", "Community access"], cta: "Start Free", highlight: false },
  { name: "OPERATOR", price: "R 199", sub: "/month", features: ["Unlimited AI generations", "Full Prompt Vault (500+)", "Solopreneur OS included", "WhatsApp AI bot access", "Priority support"], cta: "Go Operator →", highlight: true },
  { name: "EMPIRE", price: "R 499", sub: "/month", features: ["Everything in Operator", "AI content auto-scheduler", "Client Command Kit", "PropelAI early access", "1-on-1 AI strategy call"], cta: "Build Empire →", highlight: false },
];

/* ── SVG LOGO ── */
function Logo({ size = 48 }) {
  return (
    <svg width={size} height={size} viewBox="0 0 100 100" fill="none">
      <defs>
        <linearGradient id="lg1" x1="0" y1="0" x2="100" y2="100" gradientUnits="userSpaceOnUse">
          <stop offset="0%" stopColor={COLORS.amber} />
          <stop offset="100%" stopColor={COLORS.electric} />
        </linearGradient>
        <linearGradient id="lg2" x1="0" y1="0" x2="100" y2="100" gradientUnits="userSpaceOnUse">
          <stop offset="0%" stopColor="#1A1A22" />
          <stop offset="100%" stopColor="#0D0D12" />
        </linearGradient>
        <filter id="glow">
          <feGaussianBlur stdDeviation="2" result="blur" />
          <feComposite in="SourceGraphic" in2="blur" operator="over" />
        </filter>
      </defs>
      <polygon points="50,4 93,27.5 93,72.5 50,96 7,72.5 7,27.5" fill="url(#lg2)" stroke="url(#lg1)" strokeWidth="2.5" />
      <path d="M45 22 L55 22 L60 30 L62 40 L60 52 L55 62 L50 72 L45 62 L40 52 L38 40 L40 30 Z" fill="url(#lg1)" opacity="0.15" />
      <text x="50" y="66" textAnchor="middle" fontFamily="Georgia, serif" fontWeight="900" fontSize="46" fill="url(#lg1)" filter="url(#glow)">A</text>
      <circle cx="22" cy="38" r="3" fill={COLORS.amber} opacity="0.7" />
      <circle cx="78" cy="38" r="3" fill={COLORS.electric} opacity="0.7" />
      <circle cx="50" cy="16" r="2.5" fill={COLORS.amber} opacity="0.5" />
      <line x1="22" y1="38" x2="38" y2="50" stroke={COLORS.amber} strokeWidth="0.8" opacity="0.4" />
      <line x1="78" y1="38" x2="62" y2="50" stroke={COLORS.electric} strokeWidth="0.8" opacity="0.4" />
      <line x1="50" y1="16" x2="50" y2="28" stroke={COLORS.amber} strokeWidth="0.8" opacity="0.4" />
    </svg>
  );
}

/* ── AI DEMO WIDGET — calls secure serverless route ── */
function AIDemoWidget() {
  const [prompt, setPrompt] = useState("");
  const [result, setResult] = useState("");
  const [loading, setLoading] = useState(false);
  const [used, setUsed] = useState(0);
  const [unlocked, setUnlocked] = useState(false);
  const FREE_LIMIT = 2;

  const DEMO_PROMPTS = [
    "Write a LinkedIn hook for an African AI startup",
    "Give me 3 cold DM openers for B2B sales in SA",
    "Create a WhatsApp broadcast for a digital product launch",
  ];

  async function generate() {
    if (!prompt.trim()) return;
    if (used >= FREE_LIMIT && !unlocked) {
      setResult("🔒 FREE LIMIT REACHED\n\nYou've used your 2 free AI generations.\n\nUpgrade to OPERATOR (R199/month) for unlimited access.\n\nTap 'Go Operator →' in the PLANS tab.");
      return;
    }
    setLoading(true);
    setResult("");
    try {
      const res = await fetch("/api/aiva", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "API error");
      setResult(data.result);
      setUsed((u) => u + 1);
    } catch (err) {
      setResult("Connection error: " + err.message);
    }
    setLoading(false);
  }

  return (
    <div style={{ background: COLORS.panel, border: `1px solid ${COLORS.border}`, borderRadius: 16, padding: 20, marginBottom: 8 }}>
      <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 14 }}>
        <span style={{ fontSize: 22 }}>🤖</span>
        <div>
          <div style={{ color: COLORS.white, fontFamily: "'Georgia', serif", fontWeight: 700, fontSize: 15 }}>AIVA — Live AI Engine</div>
          <div style={{ color: COLORS.muted, fontSize: 11 }}>{unlocked ? "∞ Unlimited" : `${FREE_LIMIT - used} free uses remaining`}</div>
        </div>
        <div style={{ marginLeft: "auto", background: used < FREE_LIMIT || unlocked ? COLORS.goldDim : "#3A0000", borderRadius: 20, padding: "3px 10px", fontSize: 10, color: used < FREE_LIMIT || unlocked ? COLORS.amber : COLORS.danger, fontWeight: 700 }}>
          {unlocked ? "OPERATOR" : used < FREE_LIMIT ? "FREE" : "LOCKED"}
        </div>
      </div>

      <div style={{ display: "flex", gap: 6, flexWrap: "wrap", marginBottom: 10 }}>
        {DEMO_PROMPTS.map((p, i) => (
          <button key={i} onClick={() => setPrompt(p)} style={{ background: COLORS.carbon, border: `1px solid ${COLORS.border}`, borderRadius: 20, padding: "4px 10px", fontSize: 10, color: COLORS.muted, cursor: "pointer", fontFamily: "monospace" }}>
            {p.slice(0, 28)}…
          </button>
        ))}
      </div>

      <textarea
        value={prompt}
        onChange={(e) => setPrompt(e.target.value)}
        placeholder="Ask AIVA anything about your business…"
        rows={3}
        style={{ width: "100%", background: COLORS.carbon, border: `1px solid ${COLORS.border}`, borderRadius: 10, padding: "10px 12px", color: COLORS.white, fontSize: 13, resize: "none", outline: "none", fontFamily: "inherit", boxSizing: "border-box" }}
      />

      <button
        onClick={generate}
        disabled={loading}
        style={{ width: "100%", marginTop: 10, background: loading ? COLORS.goldDim : `linear-gradient(135deg, ${COLORS.amber}, ${COLORS.gold})`, border: "none", borderRadius: 10, padding: "12px 0", fontWeight: 800, fontSize: 14, color: COLORS.void, cursor: loading ? "not-allowed" : "pointer", letterSpacing: 1, fontFamily: "'Georgia', serif" }}
      >
        {loading ? "AIVA IS THINKING…" : "⚡ GENERATE NOW"}
      </button>

      {result && (
        <div style={{ marginTop: 14, background: COLORS.carbon, borderRadius: 10, padding: 14, borderLeft: `3px solid ${COLORS.amber}` }}>
          <div style={{ color: COLORS.amber, fontSize: 10, fontWeight: 700, marginBottom: 6, letterSpacing: 2 }}>AIVA OUTPUT</div>
          <pre style={{ color: COLORS.white, fontSize: 12.5, lineHeight: 1.6, whiteSpace: "pre-wrap", margin: 0, fontFamily: "inherit" }}>{result}</pre>
        </div>
      )}

      {!unlocked && (
        <button onClick={() => setUnlocked(true)} style={{ width: "100%", marginTop: 10, background: "transparent", border: `1px solid ${COLORS.electric}`, borderRadius: 10, padding: "10px 0", color: COLORS.electric, fontSize: 12, fontWeight: 700, cursor: "pointer", letterSpacing: 1 }}>
          🔓 DEMO: Unlock Unlimited (Simulate Upgrade)
        </button>
      )}
    </div>
  );
}

/* ── PRODUCT CARD ── */
function ProductCard({ p, onBuy }) {
  const [tapped, setTapped] = useState(false);
  return (
    <div
      onClick={() => { setTapped(true); setTimeout(() => setTapped(false), 200); onBuy(p); }}
      style={{ background: tapped ? COLORS.carbon : COLORS.panel, border: `1px solid ${COLORS.border}`, borderRadius: 14, padding: 18, marginBottom: 12, cursor: "pointer", transform: tapped ? "scale(0.98)" : "scale(1)", transition: "all 0.15s" }}
    >
      {p.badge && <div style={{ fontSize: 10, fontWeight: 800, color: p.color, letterSpacing: 1.5, marginBottom: 6 }}>{p.badge}</div>}
      <div style={{ display: "flex", alignItems: "flex-start", gap: 12 }}>
        <div style={{ width: 44, height: 44, borderRadius: 10, background: `${p.color}18`, border: `1px solid ${p.color}44`, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 22, flexShrink: 0 }}>
          {p.icon}
        </div>
        <div style={{ flex: 1 }}>
          <div style={{ color: COLORS.muted, fontSize: 9, fontWeight: 700, letterSpacing: 2, marginBottom: 2 }}>{p.tag}</div>
          <div style={{ color: COLORS.white, fontSize: 14, fontWeight: 700, fontFamily: "'Georgia', serif", lineHeight: 1.3, marginBottom: 4 }}>{p.name}</div>
          <div style={{ color: COLORS.muted, fontSize: 12, lineHeight: 1.5 }}>{p.desc}</div>
        </div>
      </div>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginTop: 14 }}>
        <div>
          <span style={{ color: p.color, fontWeight: 900, fontSize: 20, fontFamily: "'Georgia', serif" }}>{p.price}</span>
          <span style={{ color: COLORS.muted, fontSize: 11, marginLeft: 6 }}>{p.usd}</span>
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
          <span style={{ color: COLORS.muted, fontSize: 11 }}>✓ {p.sold.toLocaleString()} sold</span>
          <div style={{ background: p.color, borderRadius: 8, padding: "6px 14px", color: COLORS.void, fontWeight: 800, fontSize: 12 }}>BUY →</div>
        </div>
      </div>
    </div>
  );
}

/* ── PLAN CARD ── */
function PlanCard({ plan }) {
  return (
    <div style={{ background: plan.highlight ? `linear-gradient(160deg, ${COLORS.goldDim}44, ${COLORS.panel})` : COLORS.panel, border: `2px solid ${plan.highlight ? COLORS.amber : COLORS.border}`, borderRadius: 16, padding: 20, marginBottom: 12, position: "relative" }}>
      {plan.highlight && (
        <div style={{ position: "absolute", top: -12, left: "50%", transform: "translateX(-50%)", background: COLORS.amber, borderRadius: 20, padding: "3px 16px", fontSize: 10, fontWeight: 900, color: COLORS.void, letterSpacing: 2, whiteSpace: "nowrap" }}>MOST POPULAR</div>
      )}
      <div style={{ color: COLORS.muted, fontSize: 10, fontWeight: 800, letterSpacing: 3, marginBottom: 4 }}>{plan.name}</div>
      <div style={{ display: "flex", alignItems: "baseline", gap: 4, marginBottom: 14 }}>
        <span style={{ color: plan.highlight ? COLORS.amber : COLORS.white, fontSize: 28, fontWeight: 900, fontFamily: "'Georgia', serif" }}>{plan.price}</span>
        <span style={{ color: COLORS.muted, fontSize: 12 }}>{plan.sub}</span>
      </div>
      {plan.features.map((f, i) => (
        <div key={i} style={{ display: "flex", gap: 8, marginBottom: 6 }}>
          <span style={{ color: COLORS.amber, fontSize: 12, marginTop: 1 }}>✦</span>
          <span style={{ color: COLORS.white, fontSize: 12.5 }}>{f}</span>
        </div>
      ))}
      <button style={{ width: "100%", marginTop: 16, background: plan.highlight ? `linear-gradient(135deg, ${COLORS.amber}, ${COLORS.gold})` : "transparent", border: plan.highlight ? "none" : `1px solid ${COLORS.border}`, borderRadius: 10, padding: "12px 0", fontWeight: 800, fontSize: 13, color: plan.highlight ? COLORS.void : COLORS.white, cursor: "pointer", letterSpacing: 1, fontFamily: "'Georgia', serif" }}>
        {plan.cta}
      </button>
    </div>
  );
}

/* ── STATS TICKER ── */
function StatsTicker() {
  const stats = ["R 47,820 revenue generated", "1,618 downloads sold", "0 employees", "9 African countries reached", "99.7% AI-automated"];
  const [idx, setIdx] = useState(0);
  useEffect(() => {
    const t = setInterval(() => setIdx((i) => (i + 1) % stats.length), 2400);
    return () => clearInterval(t);
  }, []);
  return (
    <div style={{ background: COLORS.amber, padding: "6px 16px", textAlign: "center" }}>
      <span style={{ color: COLORS.void, fontWeight: 800, fontSize: 11, letterSpacing: 1.5 }}>⚡ LIVE · {stats[idx]}</span>
    </div>
  );
}

/* ── REVENUE TRACKER ── */
function RevenueTracker() {
  const [revenue, setRevenue] = useState(47820);
  useEffect(() => {
    const t = setInterval(() => setRevenue((r) => r + Math.floor(Math.random() * 50 + 10)), 5000);
    return () => clearInterval(t);
  }, []);
  return (
    <div style={{ background: COLORS.panel, border: `1px solid ${COLORS.border}`, borderRadius: 14, padding: 18, marginBottom: 12 }}>
      <div style={{ color: COLORS.muted, fontSize: 10, fontWeight: 700, letterSpacing: 2, marginBottom: 6 }}>LIVE REVENUE COUNTER</div>
      <div style={{ display: "flex", alignItems: "baseline", gap: 8 }}>
        <span style={{ color: COLORS.amber, fontSize: 32, fontWeight: 900, fontFamily: "'Georgia', serif" }}>R {revenue.toLocaleString()}</span>
        <span style={{ color: COLORS.success, fontSize: 12, fontWeight: 700 }}>▲ LIVE</span>
      </div>
      <div style={{ display: "flex", gap: 16, marginTop: 10 }}>
        {[["0", "EMPLOYEES"], ["AI", "OPERATOR"], ["24/7", "ACTIVE"]].map(([v, l]) => (
          <div key={l} style={{ textAlign: "center" }}>
            <div style={{ color: COLORS.white, fontSize: 18, fontWeight: 900, fontFamily: "'Georgia', serif" }}>{v}</div>
            <div style={{ color: COLORS.muted, fontSize: 9, letterSpacing: 1.5 }}>{l}</div>
          </div>
        ))}
      </div>
    </div>
  );
}

/* ── TOAST ── */
function Toast({ msg, onDone }) {
  useEffect(() => { const t = setTimeout(onDone, 3000); return () => clearTimeout(t); }, [onDone]);
  return (
    <div style={{ position: "fixed", bottom: 90, left: "50%", transform: "translateX(-50%)", background: COLORS.success, borderRadius: 30, padding: "12px 24px", color: COLORS.void, fontWeight: 800, fontSize: 13, zIndex: 9999, whiteSpace: "nowrap", boxShadow: `0 8px 32px ${COLORS.success}66` }}>
      {msg}
    </div>
  );
}

/* ─────────────────────────────────────────────
   MAIN APP
   ───────────────────────────────────────────── */
export default function AIVantageAfrica() {
  const [tab, setTab] = useState("home");
  const [toast, setToast] = useState(null);
  const [cart, setCart] = useState([]);

  function handleBuy(p) {
    setCart((c) => [...c, p]);
    setToast(`✓ ${p.name} added — ${p.price}`);
  }

  const NAV = [
    { id: "home", icon: "⬡", label: "HOME" },
    { id: "aiva", icon: "🤖", label: "AIVA" },
    { id: "store", icon: "⚡", label: "STORE" },
    { id: "plans", icon: "✦", label: "PLANS" },
    { id: "about", icon: "◈", label: "ABOUT" },
  ];

  const s = {
    root: { background: COLORS.void, minHeight: "100vh", fontFamily: "'Trebuchet MS', 'Lucida Grande', sans-serif", color: COLORS.white, maxWidth: 430, margin: "0 auto", position: "relative", paddingBottom: 80 },
    scroll: { overflowY: "auto", height: "calc(100vh - 80px)" },
    nav: { position: "fixed", bottom: 0, left: "50%", transform: "translateX(-50%)", width: "100%", maxWidth: 430, background: COLORS.obsidian, borderTop: `1px solid ${COLORS.border}`, display: "flex", zIndex: 100 },
    section: { padding: "0 16px 16px" },
    h1: { fontFamily: "'Georgia', serif", fontSize: 26, fontWeight: 900, lineHeight: 1.2, margin: 0 },
    tag: { fontSize: 10, fontWeight: 800, letterSpacing: 2.5, color: COLORS.amber, marginBottom: 6 },
  };

  return (
    <div style={s.root}>
      <StatsTicker />
      <div style={s.scroll}>

        {/* HOME */}
        {tab === "home" && (
          <div>
            <div style={{ background: `radial-gradient(ellipse at 50% 0%, ${COLORS.goldDim}33 0%, transparent 70%), ${COLORS.obsidian}`, padding: "32px 20px 28px", textAlign: "center" }}>
              <Logo size={72} />
              <div style={{ marginTop: 14, ...s.h1 }}>
                <span style={{ color: COLORS.amber }}>AIVANTAGE</span><br />
                <span style={{ color: COLORS.white }}>AFRICA</span>
              </div>
              <div style={{ color: COLORS.muted, fontSize: 13, marginTop: 8, lineHeight: 1.5 }}>
                Africa's AI Advantage.<br />
                <span style={{ color: COLORS.electric }}>Zero employees. Full monetization.</span>
              </div>
              <div style={{ display: "flex", gap: 8, justifyContent: "center", marginTop: 18, flexWrap: "wrap" }}>
                {["AI-NATIVE", "AFRICA-FIRST", "ZERO HEADCOUNT"].map((t) => (
                  <span key={t} style={{ background: COLORS.carbon, border: `1px solid ${COLORS.border}`, borderRadius: 20, padding: "4px 12px", fontSize: 9, fontWeight: 800, color: COLORS.amber, letterSpacing: 2 }}>{t}</span>
                ))}
              </div>
              <button onClick={() => setTab("aiva")} style={{ marginTop: 22, background: `linear-gradient(135deg, ${COLORS.amber}, ${COLORS.gold})`, border: "none", borderRadius: 12, padding: "14px 36px", fontWeight: 900, fontSize: 15, color: COLORS.void, cursor: "pointer", letterSpacing: 1, fontFamily: "'Georgia', serif" }}>
                TRY AIVA FREE →
              </button>
            </div>
            <div style={s.section}>
              <RevenueTracker />
              <div style={{ ...s.tag, marginTop: 8 }}>WHY AIVANTAGEAFRICA</div>
              {[
                { icon: "🌍", title: "Built for Africa", body: "R-priced. SA-aware. Continental ambition." },
                { icon: "🤖", title: "AI Runs the Business", body: "No salaries. No burnout. Margins stay with the founder." },
                { icon: "⚡", title: "Instant Monetization", body: "Download products ready to sell. Cash from day one." },
                { icon: "🔁", title: "Recurring Revenue", body: "Subscription model locked in at launch. Passive by design." },
              ].map(({ icon, title, body }) => (
                <div key={title} style={{ display: "flex", gap: 14, marginBottom: 14, padding: 16, background: COLORS.panel, borderRadius: 12, border: `1px solid ${COLORS.border}` }}>
                  <span style={{ fontSize: 26 }}>{icon}</span>
                  <div>
                    <div style={{ color: COLORS.white, fontWeight: 700, fontSize: 14, fontFamily: "'Georgia', serif" }}>{title}</div>
                    <div style={{ color: COLORS.muted, fontSize: 12, marginTop: 3 }}>{body}</div>
                  </div>
                </div>
              ))}
              <div style={{ background: `linear-gradient(135deg, ${COLORS.goldDim}22, ${COLORS.panel})`, border: `1px solid ${COLORS.goldDim}`, borderRadius: 14, padding: 18, marginTop: 4 }}>
                <div style={{ color: COLORS.amber, fontSize: 10, fontWeight: 800, letterSpacing: 2, marginBottom: 10 }}>WHAT OPERATORS ARE SAYING</div>
                {[
                  { q: "Made R3,200 in the first week. No staff. Just AIVA.", a: "Thembi K. · Johannesburg" },
                  { q: "This is the operating system Africa's freelancers needed.", a: "Sipho M. · Cape Town" },
                ].map(({ q, a }) => (
                  <div key={a} style={{ marginBottom: 14 }}>
                    <div style={{ color: COLORS.white, fontSize: 13, fontStyle: "italic", lineHeight: 1.5 }}>"{q}"</div>
                    <div style={{ color: COLORS.muted, fontSize: 11, marginTop: 4 }}>— {a}</div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* AIVA */}
        {tab === "aiva" && (
          <div style={s.section}>
            <div style={{ paddingTop: 20 }}>
              <div style={s.tag}>LIVE AI ENGINE</div>
              <div style={s.h1}><span style={{ color: COLORS.amber }}>AIVA</span> is ready.</div>
              <div style={{ color: COLORS.muted, fontSize: 13, marginTop: 6, marginBottom: 18 }}>Your AI business partner. No humans needed.</div>
              <AIDemoWidget />
              <div style={{ background: COLORS.panel, border: `1px solid ${COLORS.border}`, borderRadius: 14, padding: 16, marginTop: 4 }}>
                <div style={{ color: COLORS.muted, fontSize: 10, fontWeight: 700, letterSpacing: 2, marginBottom: 10 }}>AIVA CAN DO</div>
                {["Write launch copy for your product", "Build your 30-day content calendar", "Draft investor pitch summaries", "Generate client proposals in 60 seconds", "Create WhatsApp broadcast campaigns", "Write LinkedIn hooks that convert"].map((t) => (
                  <div key={t} style={{ display: "flex", gap: 8, marginBottom: 7 }}>
                    <span style={{ color: COLORS.amber }}>✦</span>
                    <span style={{ color: COLORS.white, fontSize: 13 }}>{t}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* STORE */}
        {tab === "store" && (
          <div style={s.section}>
            <div style={{ paddingTop: 20 }}>
              <div style={s.tag}>DIGITAL PRODUCT STORE</div>
              <div style={s.h1}>Instant <span style={{ color: COLORS.amber }}>Downloads.</span></div>
              <div style={{ color: COLORS.muted, fontSize: 13, marginTop: 6, marginBottom: 18 }}>AI-built. Instant delivery. Real results.</div>
              {PRODUCTS.map((p) => <ProductCard key={p.id} p={p} onBuy={handleBuy} />)}
              {cart.length > 0 && (
                <div style={{ background: `linear-gradient(135deg, ${COLORS.goldDim}44, ${COLORS.panel})`, border: `2px solid ${COLORS.amber}`, borderRadius: 14, padding: 16, textAlign: "center" }}>
                  <div style={{ color: COLORS.amber, fontWeight: 800, fontSize: 13 }}>🛒 {cart.length} item{cart.length > 1 ? "s" : ""} in cart</div>
                  <button style={{ marginTop: 10, background: `linear-gradient(135deg, ${COLORS.amber}, ${COLORS.gold})`, border: "none", borderRadius: 10, padding: "12px 32px", fontWeight: 900, fontSize: 14, color: COLORS.void, cursor: "pointer" }}>
                    CHECKOUT NOW →
                  </button>
                </div>
              )}
            </div>
          </div>
        )}

        {/* PLANS */}
        {tab === "plans" && (
          <div style={s.section}>
            <div style={{ paddingTop: 20 }}>
              <div style={s.tag}>SUBSCRIPTION PLANS</div>
              <div style={s.h1}>Pick your <span style={{ color: COLORS.amber }}>level.</span></div>
              <div style={{ color: COLORS.muted, fontSize: 13, marginTop: 6, marginBottom: 24 }}>All plans run on AI. No contracts. Cancel anytime.</div>
              {PLANS.map((p) => <PlanCard key={p.name} plan={p} />)}
              <div style={{ background: COLORS.panel, border: `1px solid ${COLORS.border}`, borderRadius: 14, padding: 16, marginTop: 4 }}>
                <div style={{ color: COLORS.white, fontWeight: 700, fontSize: 14, marginBottom: 8, fontFamily: "'Georgia', serif" }}>🔒 100% AI-Secured. 0 Humans.</div>
                {["Instant digital delivery", "Paystack & card accepted", "Cancel anytime — no penalties", "30-day money-back guarantee"].map((t) => (
                  <div key={t} style={{ color: COLORS.muted, fontSize: 12, marginBottom: 5 }}>✓ {t}</div>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* ABOUT */}
        {tab === "about" && (
          <div style={s.section}>
            <div style={{ paddingTop: 20 }}>
              <div style={{ background: `radial-gradient(ellipse at top, ${COLORS.goldDim}33, transparent), ${COLORS.panel}`, border: `1px solid ${COLORS.border}`, borderRadius: 20, padding: 24, marginBottom: 16, textAlign: "center" }}>
                <Logo size={60} />
                <div style={{ marginTop: 14, color: COLORS.amber, fontSize: 10, fontWeight: 800, letterSpacing: 3 }}>AI FOUNDER</div>
                <div style={{ color: COLORS.white, fontSize: 22, fontWeight: 900, fontFamily: "'Georgia', serif", marginTop: 4 }}>David Mogotlane</div>
                <div style={{ color: COLORS.muted, fontSize: 12, marginTop: 4 }}>Johannesburg, South Africa</div>
                <div style={{ display: "flex", gap: 8, justifyContent: "center", marginTop: 14, flexWrap: "wrap" }}>
                  {["Founder & CEO", "CEO · AIVANTAGEAFRICA", "AI Business Factory"].map((t) => (
                    <span key={t} style={{ background: COLORS.carbon, border: `1px solid ${COLORS.border}`, borderRadius: 20, padding: "4px 12px", fontSize: 10, color: COLORS.electric, fontWeight: 700 }}>{t}</span>
                  ))}
                </div>
              </div>
              <div style={{ background: COLORS.panel, border: `1px solid ${COLORS.border}`, borderRadius: 14, padding: 18, marginBottom: 14 }}>
                <div style={{ color: COLORS.amber, fontSize: 10, fontWeight: 800, letterSpacing: 2, marginBottom: 10 }}>THE THESIS</div>
                <div style={{ color: COLORS.white, fontSize: 14, lineHeight: 1.7, fontFamily: "'Georgia', serif" }}>
                  "AI can build, operate, and monetize a business with the founder serving only as the legal and strategic vessel. AIVANTAGEAFRICA is the proof."
                </div>
              </div>
              <div style={{ background: COLORS.panel, border: `1px solid ${COLORS.border}`, borderRadius: 14, padding: 18, marginBottom: 14 }}>
                <div style={{ color: COLORS.amber, fontSize: 10, fontWeight: 800, letterSpacing: 2, marginBottom: 12 }}>AI BUSINESS FACTORY — ACTIVE VENTURES</div>
                {[
                  { name: "Axon Digital Studio", desc: "AI-native Shopify digital products", status: "LIVE" },
                  { name: "AIVANTAGEAFRICA", desc: "Africa's AI monetization platform", status: "LIVE" },
                  { name: "PropelAI", desc: "AI proposal & onboarding SaaS", status: "BUILDING" },
                ].map((v) => (
                  <div key={v.name} style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 10, paddingBottom: 10, borderBottom: `1px solid ${COLORS.border}` }}>
                    <div>
                      <div style={{ color: COLORS.white, fontWeight: 700, fontSize: 13 }}>{v.name}</div>
                      <div style={{ color: COLORS.muted, fontSize: 11 }}>{v.desc}</div>
                    </div>
                    <div style={{ background: v.status === "LIVE" ? `${COLORS.success}22` : `${COLORS.amber}22`, border: `1px solid ${v.status === "LIVE" ? COLORS.success : COLORS.amber}`, borderRadius: 20, padding: "3px 10px", fontSize: 9, fontWeight: 800, color: v.status === "LIVE" ? COLORS.success : COLORS.amber, letterSpacing: 1 }}>
                      {v.status}
                    </div>
                  </div>
                ))}
              </div>
              <div style={{ background: COLORS.panel, border: `1px solid ${COLORS.border}`, borderRadius: 14, padding: 18 }}>
                <div style={{ color: COLORS.amber, fontSize: 10, fontWeight: 800, letterSpacing: 2, marginBottom: 10 }}>CONNECT</div>
                {[
                  { icon: "💼", platform: "LinkedIn", handle: "@davidmogotlane" },
                  { icon: "📱", platform: "WhatsApp", handle: "AIVANTAGEAFRICA Channel" },
                  { icon: "🛒", platform: "Shopify Store", handle: "axondigitalstudio.co.za" },
                ].map(({ icon, platform, handle }) => (
                  <div key={platform} style={{ display: "flex", gap: 12, alignItems: "center", marginBottom: 12 }}>
                    <span style={{ fontSize: 20 }}>{icon}</span>
                    <div>
                      <div style={{ color: COLORS.muted, fontSize: 10, fontWeight: 700 }}>{platform}</div>
                      <div style={{ color: COLORS.electric, fontSize: 13, fontWeight: 600 }}>{handle}</div>
                    </div>
                  </div>
                ))}
              </div>
              <div style={{ textAlign: "center", padding: "20px 0 10px" }}>
                <div style={{ color: COLORS.muted, fontSize: 10, letterSpacing: 1 }}>© 2025 AIVANTAGEAFRICA · Built by AI · Operated by AI</div>
                <div style={{ color: COLORS.amber, fontSize: 10, fontWeight: 700, marginTop: 4, letterSpacing: 2 }}>FOUNDED BY DAVID MOGOTLANE · JOHANNESBURG</div>
              </div>
            </div>
          </div>
        )}
      </div>

      {/* BOTTOM NAV */}
      <nav style={s.nav}>
        {NAV.map(({ id, icon, label }) => (
          <button key={id} onClick={() => setTab(id)} style={{ flex: 1, padding: "10px 4px 8px", background: "none", border: "none", cursor: "pointer", display: "flex", flexDirection: "column", alignItems: "center", gap: 3 }}>
            <span style={{ fontSize: 18, color: tab === id ? COLORS.amber : COLORS.muted }}>{icon}</span>
            <span style={{ fontSize: 9, fontWeight: 700, letterSpacing: 1.5, color: tab === id ? COLORS.amber : COLORS.muted }}>{label}</span>
          </button>
        ))}
      </nav>

      {toast && <Toast msg={toast} onDone={() => setToast(null)} />}
    </div>
  );
}
